# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_choice_poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(max_length=15)),
                ('board_choice', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Msg_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=30)),
                ('time_of_day', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=15)),
                ('winds', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
