# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='msg_post',
            name='winds',
        ),
        migrations.AlterField(
            model_name='msg_post',
            name='location',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='msg_board.Location'),
        ),
    ]
