# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_board', '0002_auto_20170716_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_choice_poll',
            name='experience_level',
        ),
    ]
